# Generated by Django 4.0.1 on 2024-07-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chatmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
    ]
