# Generated by Django 4.0.1 on 2024-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_chatmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(blank=True, max_length=10000000000, null=True),
        ),
    ]
